# GHCR Image Pull Secret
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghcr-image-pull-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: riedu-eshop
    app.kubernetes.io/component: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/Aidas-dev/riedu-eshop.git
    targetRevision: main
    path: kubernetes
    directory:
      include: image-pull-secret.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: riedu-eshop
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
