# Medusa Admin Panel
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medusa-admin
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: riedu-eshop
    app.kubernetes.io/component: admin
spec:
  project: default
  source:
    repoURL: https://github.com/Aidas-dev/riedu-eshop.git
    targetRevision: main
    path: kubernetes/medusa-admin
  destination:
    server: https://kubernetes.default.svc
    namespace: riedu-eshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
