apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-admin
  namespace: riedu-eshop
  labels:
    app: medusa-admin
    component: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medusa-admin
  template:
    metadata:
      labels:
        app: medusa-admin
        component: admin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: location
                    operator: In
                    values:
                      - oracle-cloud
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: medusa-admin
          image: ghcr.io/aidas-dev/riedu-backend:latest
          ports:
            - containerPort: 7001
              name: http
              protocol: TCP
          command: ["npx", "medusa", "start"]
          args: ["--admin-only"]
          env:
            - name: NODE_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /app
              port: 7001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /app
              port: 7001
            initialDelaySeconds: 10
            periodSeconds: 5
