apiVersion: v1
kind: Service
metadata:
  name: medusa-admin
  namespace: riedu-eshop
  labels:
    app: medusa-admin
    component: admin
spec:
  selector:
    app: medusa-admin
  ports:
    - port: 7001
      targetPort: 7001
      name: http
  type: ClusterIP
