apiVersion: v1
kind: Secret
metadata:
  name: ghcr-image-pull-secret
  namespace: personal-site
type: kubernetes.io/dockerconfigjson
data:
  # TODO: Generate with: kubectl create secret docker-registry ghcr-image-pull-secret --docker-server=ghcr.io --docker-username=<github-username> --docker-password=<github-token> --dry-run=client -o json | jq -r '.data.".dockerconfigjson"'
  .dockerconfigjson: "" # Replace with base64-encoded Docker config
